version: "3.8"
services:
    flask:
      container_name: BackDocker
      restart: always
      build:
        context: ./
        args:
           http_proxy: "http://wwwafip:80"
           https_proxy: "http://wwwafip:80"
           no_proxy: "localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.afip.gob.ar,.afip.gov.ar"
      ports: 
         - 8080:8080
      depends_on:
         - mongo
         - mysql    

    mysql:
      container_name: mysql
      image: mysql:8.0.31
      ports:
          - 3306:3306
      command: >
        --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio   
          TZ: 'America/Argentina/Buenos_Aires'      
      volumes:
          - ../data/mysql:/var/lib/mysql

    mongo:
      container_name: MongoDocker
      restart: always
      image: mongo:4.4.6
      ports:
          - 27017:27017
      volumes:
        - ../data/mongo:/data/db
      depends_on:
        - mysql  



  