version: "3.8"
services:
    flask:
      container_name: flask-app
      restart: always
      build:
        context: ./
      ports: 
         - 8080:8080
      volumes:
      - .:/app
      environment:
        PYTHONUNBUFFERED: 1
      tty: true
      stdin_open: true
      depends_on:
         - mongo
         - mysql    
    mysql:
      container_name: mysql-db
      image: mysql:8.0.31
      ports:
          - 3306:3306
      command: >
        --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio   
          TZ: 'America/Argentina/Buenos_Aires'      
      volumes:
          #- ../data/mysql:/var/lib/mysql
          - ./data/mysql-datos.sql:/docker-entrypoint-initdb.d/datos.sql:ro
    mongo:
      container_name: mongo-db
      restart: always
      #image: mongo:4.4.6
      image: mongo:latest
      ports:
          - 27017:27017
      #command: --quiet
      volumes:
          - ./data/baseMongo.json:/baseMongo.json
          - ./data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      command: bash -c "chmod +x /docker-entrypoint-initdb.d/init-mongo.sh && /docker-entrypoint-initdb.d/init-mongo.sh"


      #volumes:
      #  - ./data/baseMongo.json:/docker-entrypoint-initdb.d/datos.json:ro
      #volumes:
      #  - ../data/mongo:/data/db
      #depends_on:
      #  - mysql  
      #command: --quiet