version: "3.3"
services:

    db:
      container_name: MysqlDocker
      image: mysql
      ports:
          - 33060:3306
      command: --default-authentication-plugin=mysql_native_password
      
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio
         
      volumes:
          - ~/docker/mysql-data:/Documentos/pruebas/mysql
    mongo:
      container_name: MongoDocker
      image: mongo
      ports:
          - 27017:27017
    flask:
      container_name: backDocker
      image: back
      ports: 
         - 8080:8080
      environment:
         - MONGO_URI=mongodb://mongo:27017/todos
         - APP_PORT=5000
      depends_on:
         - mongo
         - db
