version: "3.7"
services:
    mysql:
      container_name: MysqlDocker
      image: mysql:8.0.17
      ports:
          - 33060:3306
      command: >
        --default-authentication-plugin=caching_sha2_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio   
          TZ: 'America/Argentina/Buenos_Aires'      
      volumes:
          - ../data/mysql:/var/lib/mysql
      cap_add:
          - SYS_NICE
      networks:
          - env_prod
    mongo:
      container_name: MongoDocker
      restart: always
      image: mongo:4.4.6
      ports:
          - 27017:27017
      volumes:
        - ../data/mongo:/data/db
      networks:
          - env_prod
    flask:
      container_name: BackDocker
      restart: always
      build:
        context: ./
      ports: 
         - 8080:8080
      links:
         - mysql
         - mongo
      networks:
         - env_prod
      depends_on:
         - mongo
         - mysql          

networks:
  env_prod:
    driver: bridge  
    driver_opts: 
            com.docker.network.enable_ipv6: "true"
  