version: "3.8"
services:
    flask:
      container_name: flask-app
      restart: always
      build:
        context: ./
      ports: 
         - 8080:8080
      depends_on:
         - mongo
         - mysql    

    mysql:
      container_name: mysql-db
      image: mysql:8.0.31
      ports:
          - 3306:3306
      command: >
        --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio   
          TZ: 'America/Argentina/Buenos_Aires'      
      volumes:
          - ../data/mysql:/var/lib/mysql

    mongo:
      container_name: mongo-db
      restart: always
      image: mongo:4.4.6
      ports:
          - 27017:27017
      volumes:
        - ../data/mongo:/data/db
      depends_on:
        - mysql  



  